---
- name: Install Common
  hosts: all
  gather_facts: true
  become: true
  tasks:

    # Login vào tài khoản docker của ta
    #- name: Login to private Docker registry
    #  ansible.builtin.docker_login:
    #    registry_url: https://hub.docker.com/r/duongtn1512
    #    username: duongnt1512
    #    password: 

    # Tải các file lên
    - name: Copy a file to target host
      copy:
        src: /home/duongnt01/Personal-project-Devops/Jenkins-CI/Data/Data.tar.gz
        dest: /home/ubuntu
    # Unzip the tar files
    - name: Unziping App.tar.gz ...
      shell: tar -xzvf /home/ubuntu/Data.tar.gz -C /home/ubuntu
    # Cài đặt docker engine, cấu hình và cấp quyền chạy docker
    - name: Install Container Engine
      shell: |
        bash /home/ubuntu/install-docker.sh
    # Chạy jenkins container bằng cái file docker compoes được tải lên
    - name: Run jenkins container
      shell: |
        docker-compose -f /home/ubuntu/compose.yaml up -d
    # Ngủ khoảng 10s
    - name: Wait for jenkins container run up
      shell: |
        sleep 10

    # Lấy ra mật khẩu cảu jenkins container
    - name: Get Jenkins Password
      command: docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword
      register: command_output

    # In ra mật khẩu qua màn hình terraform kích hoạt ansible
    - debug:
        var: command_output.stdout_lines # In ra mật khẩu Jenkins
